apiVersion: v1
kind: Service
metadata:
  name: {{ include "megascope.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "megascope.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "megascope.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
